/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as IapLp02H01RouteImport } from './routes/iap-lp02-h01'
import { Route as IndexRouteImport } from './routes/index'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const IapLp02H01Route = IapLp02H01RouteImport.update({
  id: '/iap-lp02-h01',
  path: '/iap-lp02-h01',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iap-lp02-h01': typeof IapLp02H01Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iap-lp02-h01': typeof IapLp02H01Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iap-lp02-h01': typeof IapLp02H01Route
  '/obrigado': typeof ObrigadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/iap-lp02-h01' | '/obrigado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/iap-lp02-h01' | '/obrigado'
  id: '__root__' | '/' | '/iap-lp02-h01' | '/obrigado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IapLp02H01Route: typeof IapLp02H01Route
  ObrigadoRoute: typeof ObrigadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iap-lp02-h01': {
      id: '/iap-lp02-h01'
      path: '/iap-lp02-h01'
      fullPath: '/iap-lp02-h01'
      preLoaderRoute: typeof IapLp02H01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IapLp02H01Route: IapLp02H01Route,
  ObrigadoRoute: ObrigadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
